smartcar/java-sdk

README.md, build.gradle, gradle.properties, src/main/java/com/smartcar/sdk/ApiClient.java
Fix timestamp bug using Joda-Time to parse ISO 8601 timestamps
=> Fix timestamp bug

build.gradle, gradle.properties, src/main/java/com/smartcar/sdk/ApiClient.java, src/main/java/com/smartcar/sdk/Vehicle.java, src/main/java/com/smartcar/sdk/data/VehicleOdometer.java, src/test/java/com/smartcar/sdk/VehicleTest.java
=> Fix Lock, Unlock, and Odometer

.gitignore, .travis.yml, build.gradle, docker-compose.yml, gradle.properties, src/integration/java/com/smartcar/sdk/AuthTest.java, src/integration/java/com/smartcar/sdk/IntegrationTest.java, src/integration/java/com/smartcar/sdk/IntegrationUtils.java, src/integration/java/com/smartcar/sdk/VehicleTest.java, src/main/java/com/smartcar/sdk/ApiClient.java, src/main/java/com/smartcar/sdk/AuthClient.java, src/main/java/com/smartcar/sdk/SmartcarException.java, src/main/java/com/smartcar/sdk/Vehicle.java, src/test/java/com/smartcar/sdk/ApiClientTest.java, src/test/java/com/smartcar/sdk/SmartcarExceptionTest.java, src/test/java/com/smartcar/sdk/UtilsTest.java, src/test/java/com/smartcar/sdk/VehicleTest.java
A few changes still pending, but this should add full integration test coverage.
=> Integration Tests

.codecov.yaml, .travis.yml, README.md, build.gradle
Updated codecov.io configuration to include integration test coverage.
=> Integration coverage

README.md, README.mdt, gradle.properties
readme was not regenerated for last deploy
=> update the readme

gradle.properties, src/integration/java/com/smartcar/sdk/IntegrationTest.java
Context: I changed the ID of oem-auth's `login.hbs` login button from `approval-button` to `sign-in-button`.
=> fix: Fixes broken e2e test

README.md
=> read me fix

docs/com/smartcar/sdk/Vehicle.html, docs/index-all.html, gradle.properties, src/integration/java/com/smartcar/sdk/VehicleTest.java, src/main/java/com/smartcar/sdk/Vehicle.java, src/test/java/com/smartcar/sdk/VehicleTest.java
Added vehicle has permissions to check if a vehicle contains a certain permission in prep for Connect Single Select.
=> feat: vehicle has permission

.travis.yml, README.md, gradle.properties
Example of a failing build for a check: https://travis-ci.com/smartcar/java-sdk/jobs/214933277
=> chore(ci): skip branches for tag and publish

README.md, README.mdt, docs/com/smartcar/sdk/AuthClient.AuthUrlBuilder.html, docs/index-all.html, gradle.properties, src/integration/java/com/smartcar/sdk/IntegrationTest.java, src/main/java/com/smartcar/sdk/AuthClient.java, src/test/java/com/smartcar/sdk/AuthClientTest.java
Adds single select vin to authUrlBuilder.
Note: Chose to use `setSingleSelectVin` instead of `setSingleSelectVIN`. Can do the latter if prefered.
=> Feat: Single select vin

README.md, docs/com/smartcar/sdk/BatchResponseMissingException.html, docs/com/smartcar/sdk/SmartcarException.html, docs/index-all.html, docs/serialized-form.html, gradle.properties, src/integration/java/com/smartcar/sdk/IntegrationTest.java, src/main/java/com/smartcar/sdk/SmartcarException.java, src/main/java/com/smartcar/sdk/data/BatchResponse.java, src/test/java/com/smartcar/sdk/SmartcarExceptionTest.java, src/test/java/com/smartcar/sdk/VehicleTest.java
This exposes a `getRequestId()` method on the `SmartcarException` class.
=> Surface SC-Request-Id on SmartcarException

README.md, docs/com/smartcar/sdk/Vehicle.html, docs/index-all.html, gradle.properties, src/integration/java/com/smartcar/sdk/IntegrationTest.java, src/integration/java/com/smartcar/sdk/VehicleTest.java, src/main/java/com/smartcar/sdk/Vehicle.java, src/test/java/com/smartcar/sdk/VehicleTest.java
=> feat(charge): add start stop charging

src/integration/java/com/smartcar/sdk/helpers/AuthHelpers.java, src/main/java/com/smartcar/sdk/data/BatchResponse.java, src/test/resources/BatchResponseError.json, src/test/resources/BatchResponseErrorV2.json, src/test/resources/BatchResponseErrorV2WithDetail.json, src/test/resources/BatchResponseMixed.json
Asana: https://app.asana.com/0/1122465745219696/1203288266000036/f
=> fix(batch): don't expect headers in error responses

README.md, gradle.properties, src/integration/java/com/smartcar/sdk/VehicleIntegrationTest.java, src/main/java/com/smartcar/sdk/data/BatchResponse.java
The goal of this ticket is to allow the `/batch` endpoint  to support the `GET /charge/limit` endpoint if passed.
Asana: https://app.asana.com/0/1122465745219696/1204652867148469/f
=> feat(BatchResponse/VehicleChargeLimit): Add `/charge/limit` support to `/batch`

README.md, gradle.properties, src/integration/java/com/smartcar/sdk/SmartcarTest.java, src/main/java/com/smartcar/sdk/Smartcar.java, src/main/java/com/smartcar/sdk/data/Connection.java, src/main/java/com/smartcar/sdk/data/ConnectionsFilter.java, src/main/java/com/smartcar/sdk/data/DeleteConnections.java, src/main/java/com/smartcar/sdk/data/GetConnections.java, src/main/java/com/smartcar/sdk/data/RequestPagingCursor.java, src/main/java/com/smartcar/sdk/data/ResponsePagingCursor.java, src/test/resources/DeleteConnections.json, src/test/resources/GetConnections.json
This PR adds functions in the smartcar namespace for Vehicle Management API, as well as option builders for those functions.
Asana:  https://app.asana.com/0/1205137826392826/1205221447377581
=> vehicle management functions

README.md, gradle.properties, src/integration/java/com/smartcar/sdk/SmartcarTest.java, src/main/java/com/smartcar/sdk/Vehicle.java, src/main/java/com/smartcar/sdk/data/BatchResponse.java, src/main/java/com/smartcar/sdk/data/VehicleChargingPort.java, src/main/java/com/smartcar/sdk/data/VehicleDoor.java, src/main/java/com/smartcar/sdk/data/VehicleLockStatus.java, src/main/java/com/smartcar/sdk/data/VehicleStorage.java, src/main/java/com/smartcar/sdk/data/VehicleSunroof.java, src/main/java/com/smartcar/sdk/data/VehicleWindow.java, src/test/java/com/smartcar/sdk/VehicleTest.java, src/test/resources/BatchLockStatusResponseSuccess.json, src/test/resources/GetVehicleLockStatus.json
This PR will add support for getting the lock status of a vehicle.
We create a new method in the `Vehicle` class called `lockStatus()` that will return a `VehicleLockStatus` object containing a property `isLocked` (true if vehicle is locked), and arrays of
- `VehicleDoor`
- `VehicleWindow`
- `VehicleStorage`
- `VehicleSunroof`
- and `VehicleChargingPort`
each of which have a `type` and `status`.
Asana: https://app.asana.com/0/1205281929337658/1205139255747896/f
=> feat: get VehicleLockStatus

README.md, gradle.properties, src/main/java/com/smartcar/sdk/Smartcar.java
Asana: https://app.asana.com/0/1205865610170548/1205945436037056/f
=> fix: update delete connections route to use correct HTTP method

README.md, gradle.properties, src/main/java/com/smartcar/sdk/AuthClient.java, src/test/java/com/smartcar/sdk/AuthClientTest.java
Asana: https://app.asana.com/0/1206922837439776/1206699517630752
=> feat: add builder method to add optional user param for auth url

LICENSE.md, README.md, build.gradle, gradle.properties
Asana: https://app.asana.com/0/1206944339950085/1206997010604366/f
Security patch for gson.
=> fix: update gson version - security patch

README.md, gradle.properties, src/main/java/com/smartcar/sdk/SmartcarException.java, src/test/java/com/smartcar/sdk/VehicleTest.java, src/test/resources/ErrorVehicleRateLimit.json
Asana: https://app.asana.com/0/0/1206993255628964/f
=> feat: add suggestedUserMessage to Smartcar Error

README.md, gradle.properties, src/integration/java/com/smartcar/sdk/helpers/AuthHelpers.java
This commit modifies the AuthHelpers class to return a default value when environment variables are not set, enhancing robustness and usability. It updates the getBrowser method to default to "firefox" if the "BROWSER" environment variable is not present. Additionally, the safeGetEnv method is refactored to accept a default value parameter, allowing other methods to specify fallbacks as necessary. An overload of safeGetEnv is also provided to maintain compatibility with existing calls that expect an exception if the environment variable is not defined.
=> feat: upgrade java-sdk version from 4.3.0 to 4.4.0

README.md, gradle.properties, src/main/java/com/smartcar/sdk/Vehicle.java, src/main/java/com/smartcar/sdk/data/AvailableCapacity.java, src/main/java/com/smartcar/sdk/data/BatchResponse.java, src/main/java/com/smartcar/sdk/data/SelectedCapacity.java, src/main/java/com/smartcar/sdk/data/VehicleNominalCapacity.java, src/test/java/com/smartcar/sdk/VehicleTest.java, src/test/resources/GetNominalCapacity.json
Asana: [https://app.asana.com/0/1208749461974048/1208679058843339/f](https://app.asana.com/0/1208749461974048/1208679058843339/f)
=> Nominal Capacity
